[project]
name = "auto-homelab"
version = "0.1.0"
description = "Automated Homelab project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]
