apiVersion: v1
kind: PersistentVolume
metadata:
  name: grimmory-app-data
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /test-data/grimmory/app-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grimmory-books
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /test-data/grimmory/books
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grimmory-mariadb
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /test-data/grimmory/mariadb
