apiVersion: v1
kind: Service
metadata:
  name: grimmory
  namespace: grimmory
spec:
  selector:
    app: grimmory
  ports:
    - port: 6060
      targetPort: 6060
      # nodePort only takes effect when type is NodePort.
      # Remove nodePort + change type to ClusterIP if using kubectl port-forward instead.
      nodePort: 30001
  type: NodePort
